format_version: 10
pipelines:
  ci-server:
    group: Tools1
    materials:
      git-da613e5:
        git: https://github.com/devops-prac1/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:gzgfqRgQLlorEwIT4NIabg==:kRlBS4kNBKz1KotKCmKQ6ezeA5WT21e6A/5SKjQutVY=
    stages:
      - Ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: {command: ansible-playbook, arguments: [ "-i", "ci-server-internal.priya9sdr.online,", "tools.yml", "-e", "tool_name=ci-server", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ], run_if: passed}
